### ISSUE TITLE
Tests run twice on file save

### ISSUE THREAD

**Issue by pierrre** [joefitzgerald/tester-go#14]
If you start Atom or if you disable then enable the package, the tests will run twice when you save a file.

If you uncheck then check the "Run Coverage Tool On Save" parameter, it will be fixed for the current Atom "session".

Atom version: 1.8.0
Package version: 1.0.4
OS: Linux pierre-dell-xps-15 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux
Go version: 1.6.3

**Comment by joefitzgerald** [comment]
I'm pretty certain I know what is happening. Sorry for the delay in responding. The issue is this:

* gofmt / goimports / goreturns have to be run synchronously because there is no asynchronous file save event hooks
* when the file is mutated in some way by one of the aforementioned tools 
* this generates two "file saved" events
* there is no debounce in tester-go to collect multiple save events in a short period of time

This can be solved via either:

1. Having go-plus coordinate these activities such that anything needing to be done based on file save is brokered by go-plus
2. Adding a denounce to tester-go

**Comment by pierrre** [comment]
OK.
I'm using the "goimports" tool in the "gofmt" Atom package.
Can you reproduce the issue?

**Comment by pierrre** [comment]
Thank you !
