### ISSUE TITLE
Customize highlight color?

### ISSUE THREAD

**Issue by froodian** [joefitzgerald/tester-go#32]
Hi, thank you for this package, I'm just wondering if the highlight color can be customized to be more subtle, I tried putting a css override in my Atom config but was unsuccessful.

**Comment by lloiser** [comment]
use the following css selector:

```
atom-text-editor::shadow .highlight.uncovered .region
```

_note:_ sooner or later this will not work due to the recent removal of the shadow dom (https://github.com/atom/apm/pull/615 and https://github.com/atom/atom/pull/12903) which will end up in one of the next atom releases. You probably just have to remove the `::shadow` part then.

**Comment by froodian** [comment]
Thanks!
